# Configuration for LLM models, especially for providers like OpenRouter.

# A list of models to be used with the OpenRouter provider.
# The program will use the FIRST model in this list.

openrouter_models:
  - alias: "NVIDIA Nemotron Nano 30B"
    model_name: "nvidia/nemotron-3-nano-30b-a3b:free"

  - alias: "NVIDIA Nemotron Super 120B"
    model_name: "nvidia/nemotron-3-super-120b-a12b:free"

  - alias: "OpenAI GPT OSS 120B"
    model_name: "openai/gpt-oss-120b:free"

  - alias: "Google Gemma 3 27B"
    model_name: "google/gemma-3-27b-it:free"

  - alias: "Poolside Laguna M.1"
    model_name: "poolside/laguna-m.1:free"

  - alias: "Minimax M2.5"
    model_name: "minimax/minimax-m2.5:free"

  - alias: "Moonshot Kimi K2.6"
    model_name: "moonshotai/kimi-k2.6:free"

  - alias: "Meta Llama 3.3 70B Instruct"
    model_name: "meta-llama/llama-3.3-70b-instruct:free"

  - alias: "Liquid LFM 2.5 1.2B Thinking"
    model_name: "liquid/lfm-2.5-1.2b-thinking:free"
